baseURL = "https://ateliercezar.fr/"
languageCode = "fr-fr"
title = "Atelier Cézar"
theme = "PaperMod"
defaultContentLanguage = "fr"
[pagination]
  pagerSize = 10

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowCodeCopyButtons = true
  ShowBreadCrumbs = false
  ShowPostNavLinks = true

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[[menu.main]]
  name = "Accueil"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Pratique"
  url = "/pratique/"
  weight = 10

[[menu.main]]
  name = "Ateliers"
  url = "/ateliers/"
  weight = 20

[[menu.main]]
  name = "À propos"
  url = "/apropos/"
  weight = 30

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 40

[[menu.main]]
  name = "Notes"
  url = "/notes/"
  weight = 50